const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(require('path').join(__dirname,'../index.html'),'utf8');
const script=html.match(/<script>([\s\S]*)<\/script>/)[1];
new vm.Script(script);
const fn=script.slice(script.indexOf('function dailyCalc('),script.indexOf("$('daily-form').onsubmit"));
const context={};vm.createContext(context);vm.runInContext(fn,context);
const tripFn=script.slice(script.indexOf('function roundTripTotals('),script.indexOf('function directionValues('));
vm.runInContext(tripFn,context);
const base={date:'2026-09-23',type:'general',distance:60,hours:8,hotel:3500,lodging:'paid',approved:false};
const calc=x=>context.dailyCalc({...base,...x});
assert.equal(calc({}).hotel,3000);assert.equal(calc({}).misc,400);
assert.equal(calc({distance:59.99}).hotel,null);
assert.equal(calc({distance:59.99,approved:true,hotel:2100}).hotel,2100);
assert.equal(calc({distance:29.99}).misc,0);
assert.equal(calc({distance:30,hours:4}).misc,200);
assert.equal(calc({hours:3.99}).misc,0);
assert.equal(calc({hours:7.99}).misc,200);
assert.equal(calc({hours:8}).misc,400);
assert.equal(calc({type:'special'}).hotel,null);
assert.equal(calc({type:'special',approved:true}).hotel,3000);
assert.equal(calc({type:'special',approved:true}).misc,0);
assert.equal(calc({lodging:'provided'}).hotel,0);
assert.ok(calc({date:'2024-12-31'}).blocked);
assert.ok(calc({type:'other'}).blocked);
assert.equal(Math.round(2.5*3),8);
assert.deepEqual(JSON.parse(JSON.stringify(context.roundTripTotals(['15','25'],['20','375']))),{invalid:false,outbound:40,returns:395,total:435,complete:true});
assert.equal(context.roundTripTotals(['15',''],['20']).complete,false);
assert.equal(context.roundTripTotals(['-1'],['20']).invalid,true);
assert.ok(html.includes('官方票價查詢'));
assert.equal((html.match(/"example":/g)||[]).length,29);
console.log('PASS: JavaScript syntax + 21 calculation/content checks');
