const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const script=html.match(/<script>([\s\S]*)<\/script>/)[1];
new vm.Script(script);

const dailySource=script.slice(script.indexOf('function dailyCalc('),script.indexOf('function addDay('));
const eligibilitySource=script.match(/function isLegEligible\([^}]+}/)[0];
const context={};vm.createContext(context);vm.runInContext(dailySource+'\n'+eligibilitySource,context);
const base={date:'2026-10-05',type:'general',distance:60,hours:8,hotel:3500,lodging:'paid',approved:false};
const calc=x=>context.dailyCalc({...base,...x});

assert.equal(calc({}).hotel,3000);assert.equal(calc({}).misc,400);
assert.equal(calc({distance:59.99}).hotel,null);
assert.equal(calc({distance:59.99,approved:true,hotel:2100}).hotel,2100);
assert.equal(calc({distance:29.99}).misc,0);
assert.equal(calc({distance:30,hours:4}).misc,200);
assert.equal(calc({hours:3.99}).misc,0);
assert.equal(calc({hours:7.99}).misc,200);
assert.equal(calc({hours:8}).misc,400);
assert.equal(calc({type:'special'}).hotel,null);
assert.equal(calc({type:'special',approved:true}).hotel,3000);
assert.equal(calc({type:'special',approved:true}).misc,0);
assert.equal(calc({lodging:'provided'}).hotel,0);
assert.ok(calc({date:'2024-12-31'}).blocked);
assert.ok(calc({type:'other'}).blocked);
assert.equal(context.isLegEligible('公車','general'),true);
assert.equal(context.isLegEligible('臺鐵','special'),true);
assert.equal(context.isLegEligible('捷運','special'),false);
assert.equal(context.isLegEligible('臺鐵','other'),false);

const removed=['依審核順序往下填寫','試算結果是承辦工作底稿','一條路徑完成案件初核','審查提醒集中在這裡','六步審查流程','送件前 5 項確認','115年3月彙編全文搜尋','本版仍需主計確認','下一步：試算交通費'];
removed.forEach(t=>assert.ok(!html.includes(t),`removed text remains: ${t}`));
['案件基本確認','保六一般出差常用門檻','第一步：先分案型','第二步：交通費試算','第三步：逐日試算住宿與雜費','依法必附','內規要求','承辦佐證','本案初核摘要','下載初核摘要 TXT'].forEach(t=>assert.ok(html.includes(t),`missing: ${t}`));
assert.ok(html.indexOf('案件基本確認')<html.indexOf('保六一般出差常用門檻'));
assert.ok(html.indexOf('保六一般出差常用門檻')<html.indexOf('第一步：先分案型'));
assert.ok(html.indexOf('第一步：先分案型')<html.indexOf('第二步：交通費試算'));
assert.ok(html.indexOf('第二步：交通費試算')<html.indexOf('第三步：逐日試算住宿與雜費'));
assert.ok(html.includes('id="add-day"')&&html.includes('function addDay('));
assert.ok(html.includes('id="case-summary"')&&html.includes('function evidenceGaps('));
assert.ok(html.includes('class="leg-table"')&&html.includes('data-label="列計狀態"'));
assert.ok(html.includes('逐段勾選「已核對」')&&html.includes('不代表路線或費用已核准'));
assert.ok(html.includes("caseType==='special'&&type==='臺鐵'"));
assert.ok(html.includes("t==='other'")&&html.includes('一般試算已停用'));
assert.ok(html.includes("groupMarkup('常用規定',common,true)"));
assert.ok(html.includes('@media(max-width:760px)')&&html.includes('.leg-table td::before'));
assert.ok(!html.includes('sources/internal-114.pdf')&&!html.includes('sources/compendium-11503.pdf'));
assert.ok(!html.includes('"pages":')&&!html.includes('"internal":'));
assert.ok(html.includes('臺鐵票價 ↗')&&html.includes('北捷票價 ↗'));
assert.ok(html.includes('同一車輛只由駕駛申報'));
assert.equal((html.match(/"example":/g)||[]).length,29);
console.log('PASS: JavaScript syntax + 48 calculation/content/privacy/responsive checks');
