const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(require('path').join(__dirname,'../index.html'),'utf8');
const script=html.match(/<script>([\s\S]*)<\/script>/)[1];
new vm.Script(script);
const fn=script.slice(script.indexOf('function dailyCalc('),script.indexOf("$('daily-form').onsubmit"));
const context={};vm.createContext(context);vm.runInContext(fn,context);
const tripFn=script.slice(script.indexOf('function roundTripTotals('),script.indexOf('function directionValues('));
vm.runInContext(tripFn,context);
const base={date:'2026-09-23',type:'general',distance:60,hours:8,hotel:3500,lodging:'paid',approved:false};
const calc=x=>context.dailyCalc({...base,...x});
assert.equal(calc({}).hotel,3000);assert.equal(calc({}).misc,400);
assert.equal(calc({distance:59.99}).hotel,null);
assert.equal(calc({distance:59.99,approved:true,hotel:2100}).hotel,2100);
assert.equal(calc({distance:29.99}).misc,0);
assert.equal(calc({distance:30,hours:4}).misc,200);
assert.equal(calc({hours:3.99}).misc,0);
assert.equal(calc({hours:7.99}).misc,200);
assert.equal(calc({hours:8}).misc,400);
assert.equal(calc({type:'special'}).hotel,null);
assert.equal(calc({type:'special',approved:true}).hotel,3000);
assert.equal(calc({type:'special',approved:true}).misc,0);
assert.equal(calc({lodging:'provided'}).hotel,0);
assert.ok(calc({date:'2024-12-31'}).blocked);
assert.ok(calc({type:'other'}).blocked);
assert.equal(Math.round(2.5*3),8);
assert.deepEqual(JSON.parse(JSON.stringify(context.roundTripTotals(['15','25'],['20','375']))),{invalid:false,outbound:40,returns:395,total:435,complete:true});
assert.equal(context.roundTripTotals(['15',''],['20']).complete,false);
assert.equal(context.roundTripTotals(['-1'],['20']).invalid,true);
assert.ok(!html.includes('id="fares"'));
assert.ok(html.includes('臺鐵票價 ↗')&&html.includes('北捷票價 ↗'));
assert.ok(html.includes('同車共乘：里程費只由駕駛申報')&&html.includes('其他同車人員視為搭便車'));
assert.equal((html.match(/class="case-choice/g)||[]).length,3);
assert.ok(html.includes('送件前 5 項確認')&&html.includes('max="5"'));
assert.ok(html.includes('id="guide" class="panel active flow-page"'));
assert.ok(html.includes('id="review" class="panel review-page"'));
assert.ok(html.includes('保六一般出差常用門檻')&&html.includes('第一步：先分案型')&&html.includes('第二步：交通費試算')&&html.includes('第三步：住宿、雜費試算'));
assert.ok(html.indexOf('保六一般出差常用門檻')<html.indexOf('第一步：先分案型'));
assert.ok(html.indexOf('第一步：先分案型')<html.indexOf('第二步：交通費試算'));
assert.ok(html.indexOf('第二步：交通費試算')<html.indexOf('第三步：住宿、雜費試算'));
assert.ok(html.includes('六步審查流程')&&html.includes('規定快查'));
assert.ok(html.includes('class="pet-duo"')&&html.includes('--coral:#ffb4a2')&&html.includes('--mint:#deefe7'));
assert.equal((html.match(/"example":/g)||[]).length,29);
console.log('PASS: JavaScript syntax + 34 calculation/content/layout checks');
